# Generated by Django 4.2 on 2026-01-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                choices=[("MALE", "Male"), ("FEMALE", "Female"), ("OTHER", "Other")],
                default="OTHER",
                max_length=10,
            ),
        ),
    ]
