# Generated by Django 4.2 on 2026-01-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_backend", "0002_customuser_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="nationality",
            field=models.CharField(default="GH", max_length=2),
        ),
    ]
